### ISSUE TITLE
Systemd user units

### ISSUE THREAD

**Issue by rEnr3n** [EdJoPaTo/website-stalker#12]
Please add unit files for systemd in user mode.

**Comment by EdJoPaTo** [comment]
I like the idea. Having more options sounds like a good think there. I neglected it so far because my main intention would be to run it on a headless device. But for something like the personal laptop user tasks make sense. Or do I miss another good usecase there?

For the filestructure: Maybe `systemd/system/install.sh` and `systemd/user/install.sh`?

What would be a good default working directory? With `systemctl edit` a user can change that but the default should be sane in my opinion.

Ideas:
- `$HOME/.local/share/website-stalker`
- `$HOME/.website-stalker`
- `$HOME/website-stalker`

Both .config and .cache do not seem like a good fit as the config `website-stalker.yaml` and the actual data `sites` (and potentially something like etags) are at the same place.

**Comment by rEnr3n** [comment]
> I like the idea. Having more options sounds like a good think there. I neglected it so far because my main intention would be to run it on a headless device. But for something like the personal laptop user tasks make sense. Or do I miss another good usecase there?

I installed this on my pc. User units will also be useful for servers serving multiple users.

> What would be a good default working directory?

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

I don't like clutter so I'd vote for: `$HOME/.local/share/website-stalker`

**Comment by EdJoPaTo** [comment]
> User units will also be useful for servers serving multiple users.

In that case system services with instance names equaling the username might make more sense. That might also be a good idea to add.
Inspiration: [syncthing@.service](https://github.com/syncthing/syncthing/blob/main/etc/linux-systemd/system/syncthing%40.service)

**Comment by EdJoPaTo** [comment]
@rEnr3n can you take a look on 580bb5fb69ec4dd54d8efa1c5b96f8c3ceddfba2 for a sanity check?
They should be released with 0.7.1 and the AUR files also need to be adapted.

**Comment by EdJoPaTo** [comment]
I skipped adding the system services with instance names for the users for now. Stopping, updating the binary and restarting them is not as simple as with fixed names.
If someone is interested in them, feel free to provide them with a proper install script.

user scripts are added in 580bb5f and 953a038

**Comment by EdJoPaTo** [comment]
Thanks again for your suggestion! They are available in [v0.7.1](https://github.com/EdJoPaTo/website-stalker/releases/tag/v0.7.1) now.

**Comment by rEnr3n** [comment]
Sorry for the late reply. I tried to compile it but I don't have enough time.

I think this line can be removed:
https://github.com/EdJoPaTo/website-stalker/blob/8282d6488889e7597e1ffd4e78d069cac747f329/systemd/user/install.sh#L30

**Comment by EdJoPaTo** [comment]
Good catch! Removed in 2f9dab4.
