### ISSUE TITLE
[Question] Watching status on bugs.chromium.org

### ISSUE THREAD

**Issue by rEnr3n** [EdJoPaTo/website-stalker#25]
**Describe your goal**
I want to watch the entire status box at the left part of this page: https://bugs.chromium.org/p/chromium/issues/detail?id=998903

**Expected**
I tried `'aside.metadata-container'` but it doesn't work. It says nothing was selected. I also tried the following with the same result:

`'.metadata-container'`
`'mr-issue-metadata'`
`'mr-metadata'`

**Comment by EdJoPaTo** [comment]
I like seeing website-stalker is being used in the wild!

That page is generated via JavaScript within the browser. When using the Developer Tools you can inspect the plain sources. Also with website-stalker you can get the plain sources without any editors.
The content of interest is simply not there yet and will be loaded via JavaScript.

Doing something like that requires basically a whole browser. Theoretically this is possible to do but its a huge effort and prone to strange cases. Also I don't know the state of stuff like that with Rust.
Also: This would introduce a lot of traffic as many things will be crawled each time instead of just a single URL. That's way less friendly to the webserver.

What helps me in these cases: Developer Tools Network Tab.
There is some loaded content (Fetch/XHR) which contains the information of interest.
In your case it seems to be https://bugs.chromium.org/prpc/monorail.Issues/GetIssue but with a POST body which contains the "arguments".

Having the ability to supply some body and do a POST request instead of a GET request might be interesting but I don't know how many usecases for that might be. (= If its worth the additional complexity.)

Something that can be added for sure are JSON related editors (prettify / key selection somewhat like [jq](https://stedolan.github.io/jq/))

**Comment by EdJoPaTo** [comment]
A new editor `json_prettify` was introduced in 73814fb03d26163c9212ccdc5ab3154d6790c4f6 which will be available in v0.12.

There is no POST request or json key selection like jq does yet.
It probably would be a little bit more complicated and so far I hadn't the need for it personally.
